#!/bin/sh
# /etc/init.d/orobot-boot

### BEGIN INIT INFO
# Provides:          orobot-boot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# glogg /home/pi/orobot-firmware/tmp/* &
# sudo /home/pi/orobot-firmware/retry-client.sh >> /home/pi/orobot-firmware/tmp/reboot.log
